# Generated by Django 3.2 on 2021-06-06 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canton_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=15)),
                ('contract_date', models.DateField()),
                ('start_work_date', models.DateField()),
                ('end_work_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract_duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dutration', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contract_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=3, unique=True)),
                ('contribution_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('taxe_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('salary_account', models.CharField(max_length=10)),
                ('contribution_account', models.CharField(max_length=10)),
                ('taxe_account', models.CharField(max_length=10)),
                ('solidarity_account', models.CharField(max_length=10)),
                ('transport_account', models.CharField(max_length=10)),
                ('food_account', models.CharField(max_length=10)),
                ('cost_bruto_salary_account', models.CharField(max_length=10)),
                ('cost_transport_account', models.CharField(max_length=10)),
                ('cost_food_account', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CountryEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.IntegerField()),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('payroll_date', models.DateField()),
                ('payroll_of_date', models.DateField()),
                ('payroll_to_date', models.DateField()),
                ('worked_days', models.DecimalField(decimal_places=2, max_digits=6)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('contributions', models.DecimalField(decimal_places=2, max_digits=6)),
                ('taxe', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_name', models.CharField(max_length=100)),
                ('municipality_code', models.CharField(max_length=3)),
                ('canton', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obracun.canton')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obracun.country')),
                ('country_entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obracun.countryentity')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmbg', models.CharField(error_messages={'unique': 'Matični broj već postoji u bazi.'}, max_length=13, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('parent_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('prof_qualification', models.CharField(max_length=100)),
                ('educ_institution', models.CharField(max_length=100)),
                ('prof_title', models.CharField(max_length=100)),
                ('year_of_services', models.DecimalField(decimal_places=2, max_digits=6)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obracun.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Contract_annex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annex_date', models.DateField()),
                ('annex_number', models.CharField(max_length=15)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obracun.contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obracun.contract_duration'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obracun.contract_type'),
        ),
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obracun.employee'),
        ),
    ]
