# Generated by Django 3.2.4 on 2021-07-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obracun', '0004_alter_municipality_canton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='canton',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='country',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='country_entity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
