# Generated by Django 3.2.4 on 2021-07-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obracun', '0005_auto_20210713_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='canton',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
