# Generated by Django 3.2.4 on 2021-07-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obracun', '0007_alter_municipality_canton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='canton',
            field=models.IntegerField(blank=True, choices=[('', '---------'), (1, 'Sarajevski kanton'), (2, 'Unsko Sanski Kanton'), (3, 'Zenicko Dobojski Kanton')], null=True),
        ),
    ]
