# Generated by Django 3.2.4 on 2021-07-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obracun', '0002_auto_20210713_1527'),
        ('obracun', '0009_alter_municipality_canton'),
    ]

    operations = [
    ]
