# Generated by Django 3.2.4 on 2021-07-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obracun', '0011_alter_municipality_canton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='municipality',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
