# Generated by Django 3.2.4 on 2021-07-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obracun', '0014_auto_20210714_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract_duration',
            old_name='dutration',
            new_name='duration',
        ),
    ]
