# Generated by Django 3.2.4 on 2021-07-18 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obracun', '0016_alter_contract_end_work_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obracun.municipality'),
        ),
    ]
