# Generated by Django 3.2.4 on 2021-07-18 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obracun', '0019_auto_20210718_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obracun.employee', unique=True),
        ),
    ]
