# Generated by Django 3.2.4 on 2021-08-11 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obracun', '0022_auto_20210729_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_annex',
            name='annex_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
